doc: adicionando especificação do diagrama de entidades
PaperClip-Computer/modulo6 pull request #3
Opened 2022-06-28 02:52 UTC by Ellian-aragao

2022-07-01 23:27 UTC, CinthiaNagahama requested changes
Achei que tá muito bom, mas pode ser uma boa colocar um id no Usuário e no Médico

2022-07-04 17:20 UTC, Ellian-aragao commented
> Achei que tá muito bom, mas pode ser uma boa colocar um id no Usuário e no Médico

em questão do professor, na aula de Engenharia de Software 2, ele havia abstraído a necessidade dos IDs, por tal questão, fiz o mesmo neste quesito

2022-07-05 14:25 UTC, CinthiaNagahama approved these changes

2022-07-06 00:44 UTC, henrique-tavares approved these changes
👌

2022-07-07 17:06 UTC, merged